buildscript {
    repositories {
        maven { url = "https://maven.minecraftforge.net/" }
        maven { url = "https://repo.spongepowered.org/maven/" }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
        classpath 'org.spongepowered:mixingradle:0.6-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'org.spongepowered.mixin'

group = 'elixe'
archivesBaseName = 'elixe'
version = project.mod_version

sourceCompatibility = targetCompatibility = '1.8'
compileJava {
    options.encoding = 'UTF-8'
}

minecraft {
    version = project.forge_version
    runDir = 'run'
    mappings = project.mcp_mappings
    // makeObfSourceJar = false
}

dependencies {
    // SpongePowered Mixin
    compile('org.spongepowered:mixin:0.7.11-SNAPSHOT') {
        exclude module: 'launchwrapper'
        exclude module: 'guava'
        exclude module: 'commons-io'
        exclude module: 'gson'
        exclude module: 'commons-lang'
    }
}

mixin {
    add sourceSets.main, "mixins.elixe.refmap.json"
    defaultObfuscationEnv notch
}

processResources {
    // Replace tokens in mcmod.info
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcversion': project.minecraft.version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

jar {
    manifest {
        attributes(
            'TweakClass': 'org.spongepowered.asm.launch.MixinTweaker',
            'TweakOrder': 0,
            'MixinConfigs': 'mixins.elixe.json',
            'FMLCorePlugin': 'elixe.core.ElixeCoreMod',
            'FMLCorePluginContainsFMLMod': 'true'
        )
    }
}

// Dev runClient needs the coremod to bootstrap Mixin in the dev environment
runClient {
    jvmArgs = [
        '-Dfml.coreMods.load=elixe.core.ElixeCoreMod',
        '-Dmixin.debug=true'
    ]
}
